### ISSUE TITLE
Null-Safety Support

### ISSUE THREAD

**Issue by sageata** [clean/lineawesome_icons#2]
Null-safety support, please :D

**Comment by peengle** [comment]
Null-Safety support has been released https://pub.dev/packages/line_awesome_flutter/versions/1.1.0-nullsafety

**Comment by sageata** [comment]
> Null-Safety support has been released https://pub.dev/packages/line_awesome_flutter/versions/1.1.0-nullsafety

Thank you! Amazing job!
